xwindows:
  - xorg-server
  - xorg-apps
  - xorg-xinit
  - lightdm
  - lightdm-gtk-greeter
  - lightdm-gtk-greeter-settings
  - rofi
terminal:
  - alacritty
  - vim
  - ctags
  - cargo
fonts:
  - noto-fonts-cjk
browser:
  - chromium

